#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/pysloc
  
  autopep8 -air src 
  autopep8 -ai tests/commentsForPy  tests/*.py
  echo "not styling test/ subdir"
  
else
  echo "DEV_BASE is not defined"
fi
