#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/pysloc
  
  autopep8 -ai -r pysloc 
  autopep8 -ai commentsForPy pySloc *.py
  echo "not styling test/ subdir"
  
else
  echo "DEV_BASE is not defined"
fi
