#!/usr/bin/env python3

# testRe2cComments.py

import os
import sys
import unittest
from argparse import Namespace

from pysloc import (__version__, __version_date__,
                    RE2C_RE,
                    countLinesInDir, countLinesRe2c,
                    Q)


class TestRe2cComments (unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    # utility functions #############################################

    # actual unit tests #############################################

    def testFirstLinePat(self):

        badLine = '/* Generated by re2c N.NN.N */'
        m = RE2C_RE.match(badLine)
        self.assertEqual(m, None)

        goodLine = '/* Generated by re2c 1.22.333 */'
        m = RE2C_RE.match(goodLine)
        self.assertNotEqual(m, None)
        s = m.group(0)
        self.assertTrue(s.startswith('/* Generated by'))

    def testNameToFuncMap(self):
        testFile = './commentsForRe2c'
        options = Namespace()
        options.already = set()
        options.exRE = None
        options.q = Q()
        options.verbose = False

        lines, sloc = countLinesRe2c(testFile, options, 'gperf')
        self.assertEqual(lines, 5)
        self.assertEqual(sloc, 2)


if __name__ == '__main__':
    unittest.main()
