#!/usr/bin/env python3
# testRe2cComments.py

""" Test line counters for re2c. """

import unittest
from argparse import Namespace

from pysloc import (RE2C_RE, count_lines_re2c, MapHolder)


class TestRe2cComments(unittest.TestCase):
    """ Test line counters for re2c. """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_first_line_pat(self):
        """ Verify that the first line pattern matcher works correctly. """

        bad_line = '/* Generated by re2c N.NN.N */'
        map_ = RE2C_RE.match(bad_line)
        self.assertEqual(map_, None)

        good_line = '/* Generated by re2c 1.22.333 */'
        map_ = RE2C_RE.match(good_line)
        self.assertNotEqual(map_, None)
        sloc_ = map_.group(0)
        self.assertTrue(sloc_.startswith('/* Generated by'))

    def test_name_to_func_map(self):
        """ Verify that line counts for a known re2c document are correct. """

        test_file = 'tests/commentsForRe2c'
        options = Namespace()
        options.already = set()
        options.ex_re = None
        options.map_holder = MapHolder()
        options.verbose = False

        lines, sloc = count_lines_re2c(test_file, options, 'gperf')
        self.assertEqual(lines, 5)
        self.assertEqual(sloc, 2)


if __name__ == '__main__':
    unittest.main()
