projConfig.toml for pysloc

[meta]
    version = '0.1.0'

[project]
    name = 'pysloc'  # distro name
    package = 'pysloc'  # internal name
    proj_dir = '/home/jdd/dev/py/pysloc'
    main_lang = 'py'
    version = '0.9.3'
    version_date = '2017-10-06'
    author = 'Jim Dixon'
    author_email = 'jddixon@gmail.com'
    copyright = '2012-2017'
    description = 'counts source lines of code for various languages'
    dev_status = 'beta'
    license = 'mit'
    state = 'shared'
    url = 'https://jddixon.github.io/pysloc'

[py]
    packages=['pysloc']
    package_dir = ['src']
    test_dir = ['tests']
    py_modules=[]
    scripts=['src/pySloc']
    ext_modules=[]

    # sdReq output
    distshare=['optionz', 'xlattice_py']
    env_vars=['DVCZ_DIR']
    requirements=['bs4', 'setuptools']
    test_requirements=[]
